FROM node:14.5.0-alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

COPY . /usr/src

RUN yarn install

ENV NEXT_PUBLIC_apiKey $NEXT_PUBLIC_apiKey
ENV NEXT_PUBLIC_authDomain $NEXT_PUBLIC_authDomain
ENV NEXT_PUBLIC_databaseURL $NEXT_PUBLIC_databaseURL
ENV NEXT_PUBLIC_projectId $NEXT_PUBLIC_projectId
ENV NEXT_PUBLIC_STORAGE_BUCKET $NEXT_PUBLIC_STORAGE_BUCKET
ENV NEXT_PUBLIC_messagingSenderId $NEXT_PUBLIC_messagingSenderId
ENV NEXT_PUBLIC_appId $NEXT_PUBLIC_appId
ENV NEXT_PUBLIC_measurementId $NEXT_PUBLIC_measurementId
ENV NEXT_PUBLIC_NODE_ENV $NEXT_PUBLIC_NODE_ENV
ENV NEXT_PUBLIC_FRONTEND_ADDRESS $NEXT_PUBLIC_FRONTEND_ADDRESS

RUN yarn build:next
RUN yarn build:server
EXPOSE 3000
CMD yarn start
