name: CI_TEST

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.5]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: yarn install

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ matrix.node-version }}

      - name: test
        run: yarn test
