import { IImage } from '.';

export const imgs = [
  'https://pbs.twimg.com/media/Ek2MCwyU0AAKAmW.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ek16IfrVgAA8nEJ.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek1xLA1VkAA9G7t.png?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkxYEKiVcAEzKcg.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkxYELKU0AcWLq5.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2EXhvUcAABYj5.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2MLLgU0AMaoVp.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek1jaAvVMAEEnSq.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek18GqmVgAAenB4.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/EkzJSh0U8AAjxLs.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkzJSh2VoAES9Rt.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkzJSh0UcAEM5Cn.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkzJSh0UcAAdUJG.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2KRepU8AEMIZU.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2KS8vU8AA13mS.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2FkiOUYAATtAT.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2FlEiU0AAPUK7.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2L-uyVkAAXID7.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekcy0bHXgAAn9s3.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/EkmKdjkVgAAiPP7.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2L5UUUUAAKnp8.png?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkxTXL3VMAAFtP0.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkxTd4WU0AE68ZE.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek1-twPU0AIa8Ua.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ekw7CgbVkAAVAvu.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EksI4SaXYAAsmMS.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2Ll4EUcAA8siv.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek17Z2SUUAAKI54.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek17ly1UUAIMMfr.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkqwUgyUcAAr9F_.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek1bNJCVgAIupBM.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/EkpBizEVoAAbHjU.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ekfh52IVMAAumVM.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkzlMSAVkAE7dis.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkzlNdVVkAEGM5Q.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ek0BAzFVMAEG7Uf.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/EkyEDTQUYAIsocm.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkyEFcUU8AIFHFp.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekw9DYkU0AAGLJX.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekw9DYmVMAAzAiZ.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EkxR1paVcAAG7Wj.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek17ly1UUAIMMfr.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/Ek17ly1UUAIMMfr.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/Ek17ly1UUAIMMfr.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EkxR1paVcAAG7Wj.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekd2zM1VMAAFQ19.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekd2zM1VMAAFQ19.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekd2zM1VMAAFQ19.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Eks59ezVcAAts0M.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksKYT8UYAM8VKf.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKZRSVcAE-ufe.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKaDvVkAAl15l.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKa1XVcAEV1CE.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKYT8UYAM8VKf.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKZRSVcAE-ufe.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKaDvVkAAl15l.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKa1XVcAEV1CE.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKYT8UYAM8VKf.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKZRSVcAE-ufe.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKaDvVkAAl15l.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKa1XVcAEV1CE.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKYT8UYAM8VKf.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKZRSVcAE-ufe.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKaDvVkAAl15l.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksKa1XVcAEV1CE.jpg?format=jpg&name=360x360',
  'https://pbs.twimg.com/media/EksmbW2VkAEj2KG.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksdjzwU8AA8boy.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksdjzwU8AA8boy.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksmbW2VkAEj2KG.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksmbW2VkAEj2KG.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/EksdjzwU8AA8boy.jpg?format=jpg&name=small',
  'https://pbs.twimg.com/media/Ekx5s7sU8AAhmt2.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ekx5th_VgAAMHLV.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ekx5uygVcAAnS-u.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ek2Bs-KU0AA-WEO.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkzmLmuVMAIVIDr.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/EkzmL6wVkAAHi0H.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ek2Hj-xU0AExdnj.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek2CevoVoAESRlp.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek1ux1lUcAE6e2_.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek2BF7sUYAAqxJW.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EYnNy5dU8AEZgd9.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek19OSbVcAA8e7A.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek1pcvJVoAc_u_y.jpg?format=jpg&name=900x900',
  'https://pbs.twimg.com/media/Ek1z4pTVMAAxG_m.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek0yIDjVkAAPELx.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek10WOhUYAAdBJ7.png?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek10W5xVMAAYAUI.png?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek10XhIUYAAO7h4.png?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek10YIXVkAApvw4.png?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ek1wbk5XYAAHsqp.jpg?format=jpg&name=large',
  'https://pbs.twimg.com/media/Ek0vdfwU0AUzSvj.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/EkwlNqoVMAEdBei.jpg?format=jpg&name=medium',
  'https://pbs.twimg.com/media/Ekz0NznUUAANYC6.jpg?format=jpg&name=medium',
];

const user = ['みりん', 'ぱんつ'];
const title = '気化熱';
const caption = 'きゃぷしょーん';

export const TestImages: IImage[] = imgs.map((img, idx) => ({
  id: idx,
  src: img,
  user: user[idx % user.length],
  title,
  caption,
  isPublic: idx % 2 === 0,
}));
